package batata

import "fmt"

type Language int

const (
	LangSpanish    Language = 1
	LangEnglish    Language = 2
	LangHindi      Language = 3
	LangPortuguese Language = 4
	LangBengali    Language = 5
	LangRussian    Language = 6
	LangJapanese   Language = 7
	LangPunjabi    Language = 8
	LangVietnamese Language = 9
	LangGerman     Language = 10
	LangFrench     Language = 11
	LangItalian    Language = 12
	LangArabic     Language = 13
	LangTurkish    Language = 14
	LangIndonesian Language = 15
)

var SupportedLanguages = []string{
	"Español (Spanish)",
	"English",
	"हिन्दी (Hindi)",
	"Português (Portuguese)",
	"বাংলা (Bengali)",
	"Русский (Russian)",
	"日本語 (Japanese)",
	"ਪੰਜਾਬੀ (Western Punjabi)",
	"Tiếng Việt (Vietnamese)",
	"Deutsch (German)",
	"Français (French)",
	"Italiano (Italian)",
	"العربية (Arabic)",
	"Türkçe (Turkish)",
	"Bahasa Indonesia (Indonesian)",
}

type Strings struct {
	Intro                    string
	ChooseLLM                string
	LLMOptions               string
	OllamaConfig             string
	CerebrasConfig           string
	CerebrasKey              string
	CerebrasModel            string
	OllamaHost               string
	OllamaPort               string
	OllamaModel              string
	ConfigSaved              string
	MenuTitle                string
	MenuOptions              string
	KillGoodbye              string
	InvalidInput             string
	BackToBlady              string
	MiscConfig               string
	SetBrain                 string
	BrainOffline             string
	InvalidLanguageChoice    string
	BrainSetOllama           string
	BrainSetCerebras         string
	BrainSetNone             string
	BladyRunning             string
	InvalidCerebrasKey       string
	BrainError               string
	BrainErrorSuggest        string
	MediaStored              string
	TranscriptionConfig      string
	TranscriptionServerURL   string
	TranscriptionSaved       string
	TranscriptionSetupPrompt string
}

var LangStrings = map[Language]Strings{
	LangSpanish: {
		Intro:                    "🥔 ¡Hola! Soy Batata, el núcleo tonto que maneja la infraestructura básica de Blady. ¡Configuremos todo!",
		ChooseLLM:                "🤖 ¿Qué motor LLM?",
		LLMOptions:               "1. Ollama\n2. Cerebras\n3. Ninguno",
		OllamaConfig:             "⚙️ Configurando Ollama...",
		CerebrasConfig:           "☁️ Configurando Cerebras. Nota: Los contactos y mensajes se enviarán a Cerebras.",
		CerebrasKey:              "🔑 Ingresa tu API Key de Cerebras (cuota gratis disponible):",
		CerebrasModel:            "🤖 Elige el Modelo de Cerebras:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:               "🌐 Ingresa el Host de Ollama (IP/URL):",
		OllamaPort:               "🔌 Ingresa el Puerto de Ollama (default 11434):",
		OllamaModel:              "🤖 Ingresa el Modelo de Ollama (sugerido: gpt-oss:20b o qwen30b+):",
		ConfigSaved:              "✅ ¡Batata configurada! Di 'Batata help' cuando quieras cambiar algo.",
		MenuTitle:                "🥔 Menú Batata",
		MenuOptions:              "1. 🌍 Cambiar idioma\n2. ⚙️ Config LLM\n3. 🧠 Cerebro de Blady\n4. 🎙️ Config Transcripción\n5. ☠️ Matar app\n6. 👋 Volver a Blady",
		KillGoodbye:              "☠️ Matando whatsabladerunner... ¡Chau!",
		InvalidInput:             "❌ Entrada inválida, intenta de nuevo.",
		BackToBlady:              "👋 ¡Devolviendo control a Blady!",
		MiscConfig:               "🔧 Config misc no implementada aún.",
		SetBrain:                 "🧠 Elige LLM para el cerebro de Blady:",
		BrainOffline:             "⚠️ El cerebro de Blady está OFFLINE. Solo Batata disponible.",
		InvalidLanguageChoice:    "❌",
		BrainSetOllama:           "🧠 ¡Cerebro configurado a Ollama!",
		BrainSetCerebras:         "🧠 ¡Cerebro configurado a Cerebras!",
		BrainSetNone:             "🧠 Cerebro configurado a Ninguno (Offline).",
		BladyRunning:             "🤖 Blady ya está funcionando con el proveedor %s y el modelo: %s.",
		InvalidCerebrasKey:       "❌ API key demasiado corta (min 20 chars). Volviendo...",
		BrainError:               "⚠️ Error con el cerebro de Blady: %s",
		BrainErrorSuggest:        "ℹ️ Di 'Batata help' para re-configurar.",
		MediaStored:              "📦 Media guardada: %s (ID: %d)",
		TranscriptionConfig:      "🎙️ Configuración de Transcripción",
		TranscriptionServerURL:   "🌐 Ingresa URL del servidor de transcripción (ej: http://localhost:8000/v1):",
		TranscriptionSaved:       "✅ ¡Transcripción configurada!",
		TranscriptionSetupPrompt: "🎙️ ¿Configurar servidor de transcripción? (s/n)"},
	LangEnglish: {
		Intro:                    "🥔 Hey! I'm Batata, the dumb core that handles basic infrastructure for Blady. Let's set things up!",
		ChooseLLM:                "🤖 Which LLM engine?",
		LLMOptions:               "1. Ollama\n2. Cerebras\n3. None",
		OllamaConfig:             "⚙️ Configuring Ollama...",
		CerebrasConfig:           "☁️ Configuring Cerebras. Note: Contact info and messages will be sent to Cerebras.",
		CerebrasKey:              "🔑 Enter your Cerebras API Key (free quota available):",
		CerebrasModel:            "🤖 Choose Cerebras Model:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:               "🌐 Enter Ollama Host (IP/URL):",
		OllamaPort:               "🔌 Enter Ollama Port (default 11434):",
		OllamaModel:              "🤖 Enter Ollama Model (suggested: gpt-oss:20b or qwen30b+):",
		ConfigSaved:              "✅ Batata configured! Say 'Batata help' anytime to change settings.",
		MenuTitle:                "🥔 Batata Menu",
		MenuOptions:              "1. 🌍 Change language\n2. ⚙️ Update LLM config\n3. 🧠 Set Blady's brain\n4. 🎙️ Transcription Config\n5. ☠️ Kill app\n6. 👋 Back to Blady",
		KillGoodbye:              "☠️ Killing whatsabladerunner... Bye!",
		InvalidInput:             "❌ Invalid input, try again.",
		BackToBlady:              "👋 Returning control to Blady!",
		MiscConfig:               "🔧 Misc config not implemented yet.",
		SetBrain:                 "🧠 Pick LLM for Blady's brain:",
		BrainOffline:             "⚠️ Blady's brain is OFFLINE. Only Batata interactions available.",
		InvalidLanguageChoice:    "❌",
		BrainSetOllama:           "🧠 Brain set to Ollama!",
		BrainSetCerebras:         "🧠 Brain set to Cerebras!",
		BrainSetNone:             "🧠 Brain set to None (Offline).",
		BladyRunning:             "🤖 Blady is now running with provider %s and model: %s.",
		InvalidCerebrasKey:       "❌ API key too short (min 20 chars). Going back...",
		BrainError:               "⚠️ Error with Blady's brain: %s",
		BrainErrorSuggest:        "ℹ️ Say 'Batata help' to re-configure.",
		MediaStored:              "📦 Media stored: %s (ID: %d)",
		TranscriptionConfig:      "🎙️ Transcription Configuration",
		TranscriptionServerURL:   "🌐 Enter Transcription Server URL (e.g. http://localhost:8000/v1):",
		TranscriptionSaved:       "✅ Transcription configured!",
		TranscriptionSetupPrompt: "🎙️ Configure transcription server? (y/n)"},
	LangHindi: {
		Intro:                 "🥔 नमस्ते! मैं Batata हूँ, वह सरल कोर जो Blady के लिए बुनियादी ढांचे को संभालता है। आइए सब कुछ सेट करें!",
		ChooseLLM:             "🤖 कौन सा LLM इंजन?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. कोई नहीं",
		OllamaConfig:          "⚙️ Ollama कॉन्फ़िगर हो रहा है...",
		CerebrasConfig:        "☁️ Cerebras कॉन्फ़िगर हो रहा है। नोट: संपर्क जानकारी और संदेश Cerebras को भेजे जाएंगे।",
		CerebrasKey:           "🔑 अपना Cerebras API Key दर्ज करें (मुफ्त कोटा उपलब्ध):",
		CerebrasModel:         "🤖 Cerebras मॉडल चुनें:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Ollama होस्ट दर्ज करें (IP/URL):",
		OllamaPort:            "🔌 Ollama पोर्ट दर्ज करें (डिफ़ॉल्ट 11434):",
		OllamaModel:           "🤖 Ollama मॉडल दर्ज करें (सुझाव: gpt-oss:20b या qwen30b+):",
		ConfigSaved:           "✅ Batata कॉन्फ़िगर हो गया! सेटिंग्स बदलने के लिए किसी भी समय 'Batata help' कहें।",
		MenuTitle:             "🥔 Batata मेनू",
		MenuOptions:           "1. 🌍 भाषा बदलें\n2. ⚙️ LLM कॉन्फ़िग अपडेट करें\n3. 🧠 Blady का दिमाग सेट करें\n4. 🔧 अन्य कॉन्फ़िग\n5. ☠️ ऐप बंद करें\n6. 👋 Blady पर वापस जाएं",
		KillGoodbye:           "☠️ whatsabladerunner बंद हो रहा है... अलविदा!",
		InvalidInput:          "❌ अमान्य इनपुट, कृपया पुनः प्रयास करें।",
		BackToBlady:           "👋 Blady को नियंत्रण वापस दे रहा है!",
		MiscConfig:            "🔧 अन्य कॉन्फ़िग अभी तक लागू नहीं हुआ।",
		SetBrain:              "🧠 Blady के दिमाग के लिए LLM चुनें:",
		BrainOffline:          "⚠️ Blady का दिमाग ऑफ़लाइन है। केवल Batata उपलब्ध है।",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 दिमाग Ollama पर सेट किया गया!",
		BrainSetCerebras:      "🧠 दिमाग Cerebras पर सेट किया गया!",
		BrainSetNone:          "🧠 दिमाग किसी पर नहीं (ऑफ़लाइन) सेट किया गया।",
		BladyRunning:          "🤖 Blady अब %s प्रदाता और %s मॉडल के साथ चल रहा है।",
		InvalidCerebrasKey:    "❌ API key बहुत छोटी है (कम से कम 20 वर्ण)। वापस जा रहे हैं...",
		BrainError:            "⚠️ Blady के दिमाग में त्रुटि: %s",
		BrainErrorSuggest:     "ℹ️ फिर से कॉन्फ़िगर करने के लिए 'Batata help' कहें।",
		MediaStored:           "📦 मीडिया संग्रहीत: %s (ID: %d)",
	},
	LangPortuguese: {
		Intro:                 "🥔 Olá! Sou o Batata, o núcleo simples que cuida da infraestrutura básica do Blady. Vamos configurar tudo!",
		ChooseLLM:             "🤖 Qual motor LLM?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. Nenhum",
		OllamaConfig:          "⚙️ Configurando Ollama...",
		CerebrasConfig:        "☁️ Configurando Cerebras. Nota: Informações de contato e mensagens serão enviadas para o Cerebras.",
		CerebrasKey:           "🔑 Insira sua chave de API do Cerebras (cota gratuita disponível):",
		CerebrasModel:         "🤖 Escolha o modelo Cerebras:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Insira o host do Ollama (IP/URL):",
		OllamaPort:            "🔌 Insira a porta do Ollama (padrão 11434):",
		OllamaModel:           "🤖 Insira o modelo Ollama (sugerido: gpt-oss:20b ou qwen30b+):",
		ConfigSaved:           "✅ Batata configurado! Diga 'Batata help' quando quiser mudar algo.",
		MenuTitle:             "🥔 Menu Batata",
		MenuOptions:           "1. 🌍 Mudar idioma\n2. ⚙️ Atualizar config LLM\n3. 🧠 Definir cérebro do Blady\n4. 🔧 Config misc\n5. ☠️ Encerrar app\n6. 👋 Voltar ao Blady",
		KillGoodbye:           "☠️ Encerrando whatsabladerunner... Tchau!",
		InvalidInput:          "❌ Entrada inválida, tente novamente.",
		BackToBlady:           "👋 Devolvendo o controle ao Blady!",
		MiscConfig:            "🔧 Config miscelânea ainda não implementada.",
		SetBrain:              "🧠 Escolha qual LLM usar para o cérebro do Blady:",
		BrainOffline:          "⚠️ O cérebro do Blady está OFFLINE. Apenas o Batata está disponível.",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 Cérebro definido para Ollama!",
		BrainSetCerebras:      "🧠 Cérebro definido para Cerebras!",
		BrainSetNone:          "🧠 Cérebro definido como Nenhum (Offline).",
		BladyRunning:          "🤖 Blady agora está rodando com o provedor %s e modelo: %s.",
		InvalidCerebrasKey:    "❌ Chave de API muito curta (mín. 20 caracteres). Voltando...",
		BrainError:            "⚠️ Erro no cérebro do Blady: %s",
		BrainErrorSuggest:     "ℹ️ Diga 'Batata help' para reconfigurar.",
		MediaStored:           "📦 Mídia armazenada: %s (ID: %d)",
	},
	LangBengali: {
		Intro:                 "🥔 এটি Batata, একটি কম-প্রচেষ্টার সরল কোর যা whatsabladerunner-এর প্রধান Blady কোরের জন্য মৌলিক অবকাঠামো পরিচালনা করে। মৌলিক কনফিগারেশন অনুসরণ করবে।",
		ChooseLLM:             "🤖 কোন LLM ইঞ্জিন কনফিগার করবেন?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. কোনোটিই নয়",
		OllamaConfig:          "⚙️ Ollama কনফিগার করা হচ্ছে...",
		CerebrasConfig:        "☁️ Cerebras কনফিগার করা হচ্ছে। দ্রষ্টব্য: যোগাযোগের তথ্য এবং বার্তা Cerebras-এ পাঠানো হবে।",
		CerebrasKey:           "🔑 অনুগ্রহ করে আপনার Cerebras ডেভেলপার API কী লিখুন (বিনামূল্যে কোটা উপলব্ধ):",
		CerebrasModel:         "🤖 Cerebras মডেল চয়ন করুন:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Ollama হোস্ট লিখুন (IP/URL):",
		OllamaPort:            "🔌 Ollama পোর্ট লিখুন (ডিফল্ট 11434):",
		OllamaModel:           "🤖 Ollama মডেল লিখুন (প্রস্তাবিত: gpt-oss:20b বা qwen30b+):",
		ConfigSaved:           "✅ Batata কনফিগার করা হয়েছে। যখনই কনফিগ পরিবর্তন করতে চান, শুধু 'Batata help' বলুন।",
		MenuTitle:             "🥔 Batata মৌলিক মেনু:",
		MenuOptions:           "1. 🌍 ভাষা পরিবর্তন করুন\n2. ⚙️ LLM কনফিগ আপডেট করুন\n3. 🧠 Blady-এর মস্তিষ্ক সেট করুন\n4. 🔧 অন্যান্য কনফিগ আপডেট করুন\n5. ☠️ whatsabladerunner বন্ধ করুন\n6. 👋 Blady-তে ফিরে যান",
		KillGoodbye:           "☠️ whatsabladerunner বন্ধ হচ্ছে... বিদায়!",
		InvalidInput:          "❌ অবৈধ ইনপুট, পুনরায় চেষ্টা করুন।",
		BackToBlady:           "👋 Blady-কে নিয়ন্ত্রণ ফিরিয়ে দেওয়া হচ্ছে।",
		MiscConfig:            "🔧 অন্যান্য কনফিগ এখনও বাস্তবায়িত হয়নি।",
		SetBrain:              "🧠 Blady-এর মস্তিষ্কের জন্য কোন LLM ব্যবহার করবেন:",
		BrainOffline:          "⚠️ Blady-এর মস্তিষ্ক অফলাইন (কোনোটি নির্বাচিত নয়)। শুধুমাত্র Batata কোর ইন্টারঅ্যাকশন সম্ভব।",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 মস্তিষ্ক Ollama-তে সেট করা হয়েছে!",
		BrainSetCerebras:      "🧠 মস্তিষ্ক Cerebras-এ সেট করা হয়েছে!",
		BrainSetNone:          "🧠 মস্তিষ্ক কোনোটিই নয় (অফলাইন) সেট করা হয়েছে।",
		BladyRunning:          "🤖 Blady এখন %s প্রোভাইডার এবং %s মডেলের সাথে চলছে।",
		InvalidCerebrasKey:    "❌ API কী খুব ছোট (ন্যূনতম ২০ অক্ষর)। ফিরে যাচ্ছি...",
		BrainError:            "⚠️ Blady-এর মস্তিষ্কে ত্রুটি: %s",
		BrainErrorSuggest:     "ℹ️ পুনরায় কনফিগার করতে 'Batata help' বলুন।",
		MediaStored:           "📦 মিডিয়া সংরক্ষিত: %s (ID: %d)",
	},
	LangRussian: {
		Intro:                 "🥔 Привет! Я Batata, простое ядро, которое управляет базовой инфраструктурой Blady. Давайте всё настроим!",
		ChooseLLM:             "🤖 Какой движок LLM?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. Нет",
		OllamaConfig:          "⚙️ Настраиваем Ollama...",
		CerebrasConfig:        "☁️ Настраиваем Cerebras. Примечание: контакты и сообщения будут отправляться в Cerebras.",
		CerebrasKey:           "🔑 Введите ваш API Key для Cerebras (доступна бесплатная квота):",
		CerebrasModel:         "🤖 Выберите модель Cerebras:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Введите хост Ollama (IP/URL):",
		OllamaPort:            "🔌 Введите порт Ollama (по умолчанию 11434):",
		OllamaModel:           "🤖 Введите модель Ollama (рекомендуется: gpt-oss:20b или qwen30b+):",
		ConfigSaved:           "✅ Batata настроен! Скажите 'Batata help' в любой момент, чтобы изменить настройки.",
		MenuTitle:             "🥔 Меню Batata",
		MenuOptions:           "1. 🌍 Сменить язык\n2. ⚙️ Обновить конфиг LLM\n3. 🧠 Настроить мозг Blady\n4. 🔧 Прочие настройки\n5. ☠️ Убить приложение\n6. 👋 Вернуться к Blady",
		KillGoodbye:           "☠️ Убиваю whatsabladerunner... Пока!",
		InvalidInput:          "❌ Неверный ввод, попробуйте снова.",
		BackToBlady:           "👋 Возвращаю управление Blady!",
		MiscConfig:            "🔧 Прочие настройки еще не реализованы.",
		SetBrain:              "🧠 Выберите LLM для мозга Blady:",
		BrainOffline:          "⚠️ Мозг Blady ОФЛАЙН. Доступна только Batata.",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 Мозг настроен на Ollama!",
		BrainSetCerebras:      "🧠 Мозг настроен на Cerebras!",
		BrainSetNone:          "🧠 Мозг отключен (Оффлайн).",
		BladyRunning:          "🤖 Blady теперь запущен с провайдером %s и моделью: %s.",
		InvalidCerebrasKey:    "❌ API-ключ слишком короткий (минимум 20 символов). Возвращаемся...",
		BrainError:            "⚠️ Ошибка мозга Blady: %s",
		BrainErrorSuggest:     "ℹ️ Скажите 'Batata help' для перенастройки.",
		MediaStored:           "📦 Медиа сохранено: %s (ID: %d)",
	},
	LangJapanese: {
		Intro:                 "🥔 こんにちは！私はBatataです。Bladyの基本インフラを担当するシンプルなコアです。設定を始めましょう！",
		ChooseLLM:             "🤖 どのLLMエンジンを使用しますか？",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. なし",
		OllamaConfig:          "⚙️ Ollamaを設定中...",
		CerebrasConfig:        "☁️ Cerebrasを設定中。注意：連絡先情報とメッセージはCerebrasに送信されます。",
		CerebrasKey:           "🔑 Cerebras APIキーを入力してください（無料枠あり）：",
		CerebrasModel:         "🤖 Cerebrasモデルを選択してください：\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Ollamaホストを入力（IP/URL）：",
		OllamaPort:            "🔌 Ollamaポートを入力（デフォルト11434）：",
		OllamaModel:           "🤖 Ollamaモデルを入力（推奨：gpt-oss:20bまたはqwen30b+）：",
		ConfigSaved:           "✅ Batataが設定されました！設定を変更したい時はいつでも'Batata help'と言ってください。",
		MenuTitle:             "🥔 Batataメニュー",
		MenuOptions:           "1. 🌍 言語を変更\n2. ⚙️ LLM設定を更新\n3. 🧠 Bladyの脳を設定\n4. 🔧 その他の設定\n5. ☠️ アプリを終了\n6. 👋 Bladyに戻る",
		KillGoodbye:           "☠️ whatsabladerunnerを終了しています...さようなら！",
		InvalidInput:          "❌ 無効な入力です。もう一度お試しください。",
		BackToBlady:           "👋 Bladyに制御を戻しています！",
		MiscConfig:            "🔧 その他の設定はまだ実装されていません。",
		SetBrain:              "🧠 Bladyの脳に使用するLLMを選択：",
		BrainOffline:          "⚠️ Bladyの脳はオフラインです。Batataのみ利用可能です。",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 脳をOllamaに設定しました！",
		BrainSetCerebras:      "🧠 脳をCerebrasに設定しました！",
		BrainSetNone:          "🧠 脳をなし（オフライン）に設定しました。",
		BladyRunning:          "🤖 Bladyは現在、プロバイダー %s とモデル %s で動作しています。",
		InvalidCerebrasKey:    "❌ APIキーが短すぎます（最低20文字）。戻ります...",
		BrainError:            "⚠️ Bladyの脳エラー: %s",
		BrainErrorSuggest:     "ℹ️ 設定をやり直すには 'Batata help' と言ってください。",
		MediaStored:           "📦 メディアが保存されました: %s (ID: %d)",
	},
	LangPunjabi: {
		Intro:                 "🥔 ਇਹ Batata ਹੈ, ਇੱਕ ਘੱਟ-ਮਿਹਨਤ ਵਾਲਾ ਸਧਾਰਨ ਕੋਰ ਜੋ whatsabladerunner ਦੇ ਮੁੱਖ Blady ਕੋਰ ਲਈ ਬੁਨਿਆਦੀ ਢਾਂਚੇ ਦਾ ਧਿਆਨ ਰੱਖਦਾ ਹੈ। ਬੁਨਿਆਦੀ ਸੰਰਚਨਾ ਅੱਗੇ ਹੋਵੇਗੀ।",
		ChooseLLM:             "🤖 ਕਿਹੜਾ LLM ਇੰਜਣ ਸੰਰਚਿਤ ਕਰਨਾ ਹੈ?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. ਕੋਈ ਨਹੀਂ",
		OllamaConfig:          "⚙️ Ollama ਸੰਰਚਿਤ ਹੋ ਰਿਹਾ ਹੈ...",
		CerebrasConfig:        "☁️ Cerebras ਸੰਰਚਿਤ ਹੋ ਰਿਹਾ ਹੈ। ਨੋਟ: ਸੰਪਰਕ ਜਾਣਕਾਰੀ ਅਤੇ ਸੁਨੇਹੇ Cerebras ਨੂੰ ਭੇਜੇ ਜਾਣਗੇ।",
		CerebrasKey:           "🔑 ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ Cerebras ਡਿਵੈਲਪਰ API ਕੁੰਜੀ ਦਾਖਲ ਕਰੋ (ਮੁਫ਼ਤ ਕੋਟਾ ਉਪਲਬਧ):",
		CerebrasModel:         "🤖 Cerebras ਮਾਡਲ ਚੁਣੋ:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Ollama ਹੋਸਟ ਦਾਖਲ ਕਰੋ (IP/URL):",
		OllamaPort:            "🔌 Ollama ਪੋਰਟ ਦਾਖਲ ਕਰੋ (ਮੂਲ 11434):",
		OllamaModel:           "🤖 Ollama ਮਾਡਲ ਦਾਖਲ ਕਰੋ (ਸੁਝਾਅ: gpt-oss:20b ਜਾਂ qwen30b+):",
		ConfigSaved:           "✅ Batata ਸੰਰਚਿਤ ਹੋ ਗਿਆ। ਜਦੋਂ ਵੀ ਸੰਰਚਨਾ ਬਦਲਣੀ ਹੋਵੇ, ਬੱਸ 'Batata help' ਕਹੋ।",
		MenuTitle:             "🥔 Batata ਬੁਨਿਆਦੀ ਮੀਨੂ:",
		MenuOptions:           "1. 🌍 ਭਾਸ਼ਾ ਬਦਲੋ\n2. ⚙️ LLM ਸੰਰਚਨਾ ਅੱਪਡੇਟ ਕਰੋ\n3. 🧠 Blady ਦਾ ਦਿਮਾਗ ਸੈੱਟ ਕਰੋ\n4. 🔧 ਹੋਰ ਸੰਰਚਨਾ ਅੱਪਡੇਟ ਕਰੋ\n5. ☠️ whatsabladerunner ਬੰਦ ਕਰੋ\n6. 👋 Blady 'ਤੇ ਵਾਪਸ ਜਾਓ",
		KillGoodbye:           "☠️ whatsabladerunner ਬੰਦ ਹੋ ਰਿਹਾ ਹੈ... ਅਲਵਿਦਾ!",
		InvalidInput:          "❌ ਅਵੈਧ ਇਨਪੁੱਟ, ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
		BackToBlady:           "👋 Blady ਨੂੰ ਕੰਟਰੋਲ ਵਾਪਸ ਕਰ ਰਿਹਾ ਹੈ।",
		MiscConfig:            "🔧 ਹੋਰ ਸੰਰਚਨਾ ਅਜੇ ਲਾਗੂ ਨਹੀਂ ਹੋਈ।",
		SetBrain:              "🧠 Blady ਦੇ ਦਿਮਾਗ ਲਈ ਕਿਹੜਾ LLM ਵਰਤਣਾ ਹੈ:",
		BrainOffline:          "⚠️ Blady ਦਾ ਦਿਮਾਗ ਆਫਲਾਈਨ ਹੈ (ਕੋਈ ਨਹੀਂ ਚੁਣਿਆ)। ਸਿਰਫ਼ Batata ਕੋਰ ਇੰਟਰੈਕਸ਼ਨ ਸੰਭਵ ਹਨ।",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 ਦਿਮਾਗ Ollama 'ਤੇ ਸੈੱਟ ਕੀਤਾ ਗਿਆ!",
		BrainSetCerebras:      "🧠 ਦਿਮਾਗ Cerebras 'ਤੇ ਸੈੱਟ ਕੀਤਾ ਗਿਆ!",
		BrainSetNone:          "🧠 ਦਿਮਾਗ ਕੋਈ ਨਹੀਂ (ਆਫਲਾਈਨ) ਸੈੱਟ ਕੀਤਾ ਗਿਆ।",
		BladyRunning:          "🤖 Blady ਹੁਣ %s ਪ੍ਰਦਾਤਾ ਅਤੇ %s ਮਾਡਲ ਨਾਲ ਚੱਲ ਰਿਹਾ ਹੈ।",
		InvalidCerebrasKey:    "❌ API ਕੁੰਜੀ ਬਹੁਤ ਛੋਟੀ ਹੈ (ਘੱਟੋ-ਘੱਟ 20 ਅੱਖਰ)। ਵਾਪਸ ਜਾ ਰਹੇ ਹੋ...",
		BrainError:            "⚠️ Blady ਦੇ ਦਿਮਾਗ ਵਿੱਚ ਗਲਤੀ: %s",
		BrainErrorSuggest:     "ℹ️ ਮੁੜ-ਸੰਰਚਨਾ ਲਈ 'Batata help' ਕਹੋ।",
		MediaStored:           "📦 ਮੀਡੀਆ ਸਟੋਰ ਕੀਤਾ ਗਿਆ: %s (ID: %d)",
	},
	LangVietnamese: {
		Intro:                 "🥔 Đây là Batata, lõi đơn giản ít nỗ lực chịu trách nhiệm về cơ sở hạ tầng cơ bản cho lõi Blady chính của whatsabladerunner. Cấu hình cơ bản sẽ theo sau.",
		ChooseLLM:             "🤖 Cấu hình công cụ LLM nào?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. Không có",
		OllamaConfig:          "⚙️ Đang cấu hình Ollama...",
		CerebrasConfig:        "☁️ Đang cấu hình Cerebras. Lưu ý: Thông tin liên hệ và tin nhắn sẽ được gửi đến Cerebras.",
		CerebrasKey:           "🔑 Vui lòng nhập API Key nhà phát triển Cerebras của bạn (có hạn ngạch miễn phí):",
		CerebrasModel:         "🤖 Chọn mô hình Cerebras:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Nhập máy chủ Ollama (IP/URL):",
		OllamaPort:            "🔌 Nhập cổng Ollama (mặc định 11434):",
		OllamaModel:           "🤖 Nhập mô hình Ollama (đề xuất: gpt-oss:20b hoặc qwen30b+):",
		ConfigSaved:           "✅ Batata đã được cấu hình! Bất cứ khi nào bạn cần thay đổi cấu hình, chỉ cần nói 'Batata help'.",
		MenuTitle:             "🥔 Menu Cơ Bản Batata:",
		MenuOptions:           "1. 🌍 Đổi ngôn ngữ\n2. ⚙️ Cập nhật cấu hình LLM\n3. 🧠 Đặt não của Blady\n4. 🔧 Cập nhật cấu hình khác\n5. ☠️ Dừng whatsabladerunner\n6. 👋 Quay lại Blady",
		KillGoodbye:           "☠️ Đang dừng whatsabladerunner... Tạm biệt!",
		InvalidInput:          "❌ Đầu vào không hợp lệ, vui lòng thử lại.",
		BackToBlady:           "👋 Trả quyền điều khiển cho Blady.",
		MiscConfig:            "🔧 Cấu hình khác chưa được triển khai.",
		SetBrain:              "🧠 Chọn LLM nào để sử dụng cho não của Blady:",
		BrainOffline:          "⚠️ Não của Blady đang OFFLINE (Không chọn). Chỉ có thể tương tác với lõi Batata.",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 Não đã được đặt thành Ollama!",
		BrainSetCerebras:      "🧠 Não đã được đặt thành Cerebras!",
		BrainSetNone:          "🧠 Não đã được đặt thành Không có (Ngoại tuyến).",
		BladyRunning:          "🤖 Blady hiện đang chạy với nhà cung cấp %s và mô hình: %s.",
		InvalidCerebrasKey:    "❌ API key quá ngắn (tối thiểu 20 ký tự). Đang quay lại...",
		BrainError:            "⚠️ Lỗi với não của Blady: %s",
		BrainErrorSuggest:     "ℹ️ Nói 'Batata help' để cấu hình lại.",
		MediaStored:           "📦 Phương tiện đã lưu: %s (ID: %d)",
	},
	LangGerman: {
		Intro:                 "🥔 Hey! Ich bin Batata, der einfache Kern, der die grundlegende Infrastruktur für Blady verwaltet. Lass uns alles einrichten!",
		ChooseLLM:             "🤖 Welche LLM-Engine?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. Keine",
		OllamaConfig:          "⚙️ Konfiguriere Ollama...",
		CerebrasConfig:        "☁️ Konfiguriere Cerebras. Hinweis: Kontaktinfos und Nachrichten werden an Cerebras gesendet.",
		CerebrasKey:           "🔑 Gib deinen Cerebras API Key ein (kostenloses Kontingent verfügbar):",
		CerebrasModel:         "🤖 Wähle das Cerebras-Modell:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Gib den Ollama Host ein (IP/URL):",
		OllamaPort:            "🔌 Gib den Ollama Port ein (Standard 11434):",
		OllamaModel:           "🤖 Gib das Ollama Modell ein (Vorschlag: gpt-oss:20b oder qwen30b+):",
		ConfigSaved:           "✅ Batata konfiguriert! Sag jederzeit 'Batata help', um Einstellungen zu ändern.",
		MenuTitle:             "🥔 Batata Menü",
		MenuOptions:           "1. 🌍 Sprache ändern\n2. ⚙️ LLM Config ändern\n3. 🧠 Bladys Gehirn setzen\n4. 🔧 Sonstige Config\n5. ☠️ App beenden\n6. 👋 Zurück zu Blady",
		KillGoodbye:           "☠️ Beende whatsabladerunner... Tschüss!",
		InvalidInput:          "❌ Ungültige Eingabe, versuche es erneut.",
		BackToBlady:           "👋 Gebe Kontrolle zurück an Blady!",
		MiscConfig:            "🔧 Sonstige Config noch nicht implementiert.",
		SetBrain:              "🧠 Wähle LLM für Bladys Gehirn:",
		BrainOffline:          "⚠️ Bladys Gehirn ist OFFLINE. Nur Batata verfügbar.",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 Gehirn auf Ollama gesetzt!",
		BrainSetCerebras:      "🧠 Gehirn auf Cerebras gesetzt!",
		BrainSetNone:          "🧠 Gehirn auf Keine (Offline) gesetzt.",
		BladyRunning:          "🤖 Blady läuft jetzt mit dem Anbieter %s und dem Modell: %s.",
		InvalidCerebrasKey:    "❌ API-Key zu kurz (min. 20 Zeichen). Zurück...",
		BrainError:            "⚠️ Fehler mit Bladys Gehirn: %s",
		BrainErrorSuggest:     "ℹ️ Sag 'Batata help', um neu zu konfigurieren.",
		MediaStored:           "📦 Medien gespeichert: %s (ID: %d)",
	},
	LangFrench: {
		Intro:                 "🥔 Salut ! Je suis Batata, le noyau simple qui gère l'infrastructure de base pour Blady. Configurons tout ça !",
		ChooseLLM:             "🤖 Quel moteur LLM ?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. Aucun",
		OllamaConfig:          "⚙️ Configuration d'Ollama...",
		CerebrasConfig:        "☁️ Configuration de Cerebras. Note : Les informations de contact et les messages seront envoyés à Cerebras.",
		CerebrasKey:           "🔑 Entrez votre clé API Cerebras (quota gratuit disponible) :",
		CerebrasModel:         "🤖 Choisissez le modèle Cerebras :\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Entrez l'hôte Ollama (IP/URL) :",
		OllamaPort:            "🔌 Entrez le port Ollama (par défaut 11434) :",
		OllamaModel:           "🤖 Entrez le modèle Ollama (suggéré : gpt-oss:20b ou qwen30b+) :",
		ConfigSaved:           "✅ Batata configuré ! Dites 'Batata help' à tout moment pour modifier les paramètres.",
		MenuTitle:             "🥔 Menu Batata",
		MenuOptions:           "1. 🌍 Changer de langue\n2. ⚙️ Mettre à jour la config LLM\n3. 🧠 Définir le cerveau de Blady\n4. 🔧 Config diverse\n5. ☠️ Arrêter l'application\n6. 👋 Retour à Blady",
		KillGoodbye:           "☠️ Arrêt de whatsabladerunner... Au revoir !",
		InvalidInput:          "❌ Entrée invalide, réessayez.",
		BackToBlady:           "👋 Retour du contrôle à Blady !",
		MiscConfig:            "🔧 Config diverse pas encore implémentée.",
		SetBrain:              "🧠 Choisissez le LLM pour le cerveau de Blady :",
		BrainOffline:          "⚠️ Le cerveau de Blady est HORS LIGNE. Seules les interactions Batata sont disponibles.",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 Cerveau défini sur Ollama !",
		BrainSetCerebras:      "🧠 Cerveau défini sur Cerebras !",
		BrainSetNone:          "🧠 Cerveau défini sur Aucun (Hors ligne).",
		BladyRunning:          "🤖 Blady fonctionne maintenant avec le fournisseur %s et le modèle : %s.",
		InvalidCerebrasKey:    "❌ Clé API trop courte (min 20 caractères). Retour...",
		BrainError:            "⚠️ Erreur avec le cerveau de Blady : %s",
		BrainErrorSuggest:     "ℹ️ Dites 'Batata help' pour reconfigurer.",
		MediaStored:           "📦 Média stocké : %s (ID: %d)",
	},
	LangItalian: {
		Intro:                 "🥔 Ciao! Sono Batata, il nucleo semplice che gestisce l'infrastruttura di base per Blady. Configuriamo tutto!",
		ChooseLLM:             "🤖 Quale motore LLM?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. Nessuno",
		OllamaConfig:          "⚙️ Configurazione di Ollama...",
		CerebrasConfig:        "☁️ Configurazione di Cerebras. Nota: le informazioni di contatto e i messaggi saranno inviati a Cerebras.",
		CerebrasKey:           "🔑 Inserisci la tua API Key di Cerebras (quota gratuita disponibile):",
		CerebrasModel:         "🤖 Scegli il modello Cerebras:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Inserisci l'host Ollama (IP/URL):",
		OllamaPort:            "🔌 Inserisci la porta Ollama (predefinita 11434):",
		OllamaModel:           "🤖 Inserisci il modello Ollama (suggerito: gpt-oss:20b o qwen30b+):",
		ConfigSaved:           "✅ Batata configurato! Di' 'Batata help' in qualsiasi momento per modificare le impostazioni.",
		MenuTitle:             "🥔 Menu Batata",
		MenuOptions:           "1. 🌍 Cambia lingua\n2. ⚙️ Aggiorna configurazione LLM\n3. 🧠 Imposta il cervello di Blady\n4. 🔧 Configurazioni varie\n5. ☠️ Chiudi l'app\n6. 👋 Torna a Blady",
		KillGoodbye:           "☠️ Terminazione di whatsabladerunner... Ciao!",
		InvalidInput:          "❌ Input non valido, riprova.",
		BackToBlady:           "👋 Controllo restituito a Blady!",
		MiscConfig:            "🔧 Configurazioni varie non ancora implementate.",
		SetBrain:              "🧠 Scegli l'LLM per il cervello di Blady:",
		BrainOffline:          "⚠️ Il cervello di Blady è OFFLINE. Solo le interazioni con Batata sono disponibili.",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 Cervello impostato su Ollama!",
		BrainSetCerebras:      "🧠 Cervello impostato su Cerebras!",
		BrainSetNone:          "🧠 Cervello impostato su Nessuno (Offline).",
		BladyRunning:          "🤖 Blady è ora in esecuzione con il provider %s e il modello: %s.",
		InvalidCerebrasKey:    "❌ API key troppo corta (min 20 caratteri). Torno indietro...",
		BrainError:            "⚠️ Errore con il cervello di Blady: %s",
		BrainErrorSuggest:     "ℹ️ Di' 'Batata help' per riconfigurare.",
	},
	LangArabic: {
		Intro:                 "🥔 مرحبًا! أنا Batata، النواة البسيطة التي تدير البنية التحتية الأساسية لـ Blady. دعنا نقم بإعداد كل شيء!",
		ChooseLLM:             "🤖 أي محرك LLM؟",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. لا شيء",
		OllamaConfig:          "⚙️ جاري إعداد Ollama...",
		CerebrasConfig:        "☁️ جاري إعداد Cerebras. ملاحظة: سيتم إرسال معلومات الاتصال والرسائل إلى Cerebras.",
		CerebrasKey:           "🔑 أدخل مفتاح API الخاص بـ Cerebras (يتوفر حصة مجانية):",
		CerebrasModel:         "🤖 اختر نموذج Cerebras:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 أدخل مضيف Ollama (IP/URL):",
		OllamaPort:            "🔌 أدخل منفذ Ollama (الافتراضي 11434):",
		OllamaModel:           "🤖 أدخل نموذج Ollama (المقترح: gpt-oss:20b أو qwen30b+):",
		ConfigSaved:           "✅ تم تكوين Batata! قل 'Batata help' في أي وقت لتغيير الإعدادات.",
		MenuTitle:             "🥔 قائمة Batata",
		MenuOptions:           "1. 🌍 تغيير اللغة\n2. ⚙️ تحديث تكوين LLM\n3. 🧠 تعيين دماغ Blady\n4. 🔧 تكوينات متنوعة\n5. ☠️ إنهاء التطبيق\n6. 👋 العودة إلى Blady",
		KillGoodbye:           "☠️ جاري إنهاء whatsabladerunner... وداعًا!",
		InvalidInput:          "❌ إدخال غير صالح، حاول مرة أخرى.",
		BackToBlady:           "👋 جاري إعادة التحكم إلى Blady!",
		MiscConfig:            "🔧 التكوينات المتنوعة لم يتم تنفيذها بعد.",
		SetBrain:              "🧠 اختر LLM لدماغ Blady:",
		BrainOffline:          "⚠️ دماغ Blady غير متصل بالإنترنت. تفاعلات Batata فقط متاحة.",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 تم ضبط الدماغ على Ollama!",
		BrainSetCerebras:      "🧠 تم ضبط الدماغ على Cerebras!",
		BrainSetNone:          "🧠 تم ضبط الدماغ على لا شيء (غير متصل).",
		BladyRunning:          "🤖 يعمل Blady الآن مع المزود %s والطراز: %s.",
		InvalidCerebrasKey:    "❌ مفتاح API قصير جدًا (20 حرفًا على الأقل). جاري العودة...",
		BrainError:            "⚠️ خطأ في دماغ Blady: %s",
		BrainErrorSuggest:     "ℹ️ قل 'Batata help' لإعادة التكوين.",
		MediaStored:           "📦 تم تخزين الوسائط: %s (ID: %d)",
	},
	LangTurkish: {
		Intro:                 "🥔 Merhaba! Ben Batata, Blady için temel altyapıyı yöneten basit çekirdeğim. Hadi her şeyi ayarlayalım!",
		ChooseLLM:             "🤖 Hangi LLM motoru?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. Hiçbiri",
		OllamaConfig:          "⚙️ Ollama yapılandırılıyor...",
		CerebrasConfig:        "☁️ Cerebras yapılandırılıyor. Not: Kişi bilgileri ve mesajlar Cerebras'a gönderilecektir.",
		CerebrasKey:           "🔑 Cerebras API Anahtarınızı girin (ücretsiz kota mevcuttur):",
		CerebrasModel:         "🤖 Cerebras Modelini seçin:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Ollama Hostunu girin (IP/URL):",
		OllamaPort:            "🔌 Ollama Portunu girin (varsayılan 11434):",
		OllamaModel:           "🤖 Ollama Modelini girin (önerilen: gpt-oss:20b veya qwen30b+):",
		ConfigSaved:           "✅ Batata yapılandırıldı! Ayarları değiştirmek için istediğiniz zaman 'Batata help' deyin.",
		MenuTitle:             "🥔 Batata Menüsü",
		MenuOptions:           "1. 🌍 Dili değiştir\n2. ⚙️ LLM yapılandırmasını güncelle\n3. 🧠 Blady'nin beynini ayarla\n4. 🔧 Çeşitli ayarlar\n5. ☠️ Uygulamayı kapat\n6. 👋 Blady'ye dön",
		KillGoodbye:           "☠️ whatsabladerunner kapatılıyor... Hoşça kal!",
		InvalidInput:          "❌ Geçersiz giriş, tekrar deneyin.",
		BackToBlady:           "👋 Kontrol Blady'ye devrediliyor!",
		MiscConfig:            "🔧 Çeşitli ayarlar henüz uygulanmadı.",
		SetBrain:              "🧠 Blady'nin beyni için LLM seçin:",
		BrainOffline:          "⚠️ Blady'nin beyni ÇEVRİMDIŞI. Sadece Batata etkileşimleri kullanılabilir.",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 Beyin Ollama olarak ayarlandı!",
		BrainSetCerebras:      "🧠 Beyin Cerebras olarak ayarlandı!",
		BrainSetNone:          "🧠 Beyin Hiçbiri (Çevrimdışı) olarak ayarlandı.",
		BladyRunning:          "🤖 Blady şu anda %s sağlayıcısı ve %s modeli ile çalışıyor.",
		InvalidCerebrasKey:    "❌ API anahtarı çok kısa (en az 20 karakter). Geri dönülüyor...",
		BrainError:            "⚠️ Blady'nin beyninde hata: %s",
		BrainErrorSuggest:     "ℹ️ Yeniden yapılandırmak için 'Batata help' deyin.",
		MediaStored:           "📦 Medya kaydedildi: %s (ID: %d)",
	},
	LangIndonesian: {
		Intro:                 "🥔 Halo! Saya Batata, core sederhana yang menangani infrastruktur dasar untuk Blady. Ayo siapkan semuanya!",
		ChooseLLM:             "🤖 Mesin LLM yang mana?",
		LLMOptions:            "1. Ollama\n2. Cerebras\n3. Tidak ada",
		OllamaConfig:          "⚙️ Mengonfigurasi Ollama...",
		CerebrasConfig:        "☁️ Mengonfigurasi Cerebras. Catatan: Info kontak dan pesan akan dikirim ke Cerebras.",
		CerebrasKey:           "🔑 Masukkan API Key Cerebras Anda (kuota gratis tersedia):",
		CerebrasModel:         "🤖 Pilih Model Cerebras:\n1. qwen-3-235b-a22b-instruct-2507\n2. zai-glm-4.6\n3. gpt-oss-120b\n4. llama-3.3-70b",
		OllamaHost:            "🌐 Masukkan Host Ollama (IP/URL):",
		OllamaPort:            "🔌 Masukkan Port Ollama (default 11434):",
		OllamaModel:           "🤖 Masukkan Model Ollama (saran: gpt-oss:20b atau qwen30b+):",
		ConfigSaved:           "✅ Batata terkonfigurasi! Ucapkan 'Batata help' kapan saja untuk mengubah pengaturan.",
		MenuTitle:             "🥔 Menu Batata",
		MenuOptions:           "1. 🌍 Ubah bahasa\n2. ⚙️ Perbarui konfigurasi LLM\n3. 🧠 Atur otak Blady\n4. 🔧 Konfigurasi lain-lain\n5. ☠️ Hentikan aplikasi\n6. 👋 Kembali ke Blady",
		KillGoodbye:           "☠️ Menghentikan whatsabladerunner... Sampai jumpa!",
		InvalidInput:          "❌ Masukan tidak valid, coba lagi.",
		BackToBlady:           "👋 Mengembalikan kontrol ke Blady!",
		MiscConfig:            "🔧 Konfigurasi lain-lain belum diimplementasikan.",
		SetBrain:              "🧠 Pilih LLM untuk otak Blady:",
		BrainOffline:          "⚠️ Otak Blady OFFLINE. Hanya interaksi Batata yang tersedia.",
		InvalidLanguageChoice: "❌",
		BrainSetOllama:        "🧠 Otak disetel ke Ollama!",
		BrainSetCerebras:      "🧠 Otak disetel ke Cerebras!",
		BrainSetNone:          "🧠 Otak disetel ke Tidak Ada (Offline).",
		BladyRunning:          "🤖 Blady sekarang berjalan dengan penyedia %s dan model: %s.",
		InvalidCerebrasKey:    "❌ API key terlalu pendek (minimal 20 karakter). Kembali...",
		BrainError:            "⚠️ Kesalahan pada otak Blady: %s",
		BrainErrorSuggest:     "ℹ️ Ucapkan 'Batata help' untuk mengonfigurasi ulang.",
		MediaStored:           "📦 Media disimpan: %s (ID: %d)",
	},
}

func GetString(lang Language, selector func(Strings) string) string {
	strs, ok := LangStrings[lang]
	if !ok {
		strs = LangStrings[LangEnglish]
	}
	return selector(strs)
}

func LangSelectMenu() string {
	menu := ""
	for i, l := range SupportedLanguages {
		menu += fmt.Sprintf("%d. %s\n", i+1, l)
	}
	return menu
}
